# Generated by Django 4.2.2 on 2023-06-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubbucksapi', '0002_alter_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
