# Generated by Django 4.2.2 on 2023-07-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubbucksapi', '0005_transaction_total_amount_transactionitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
